# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_run_id', models.CharField(default=snippets.models.get_test_id, max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('execution', models.DateTimeField(blank=True, null=True)),
                ('test_suit_id', models.CharField(max_length=50)),
                ('test_file', models.FileField(upload_to=b'')),
                ('log_path', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('t', 'Testing'), ('c', 'Completed'), ('e', 'Error')], default='w', max_length=10)),
                ('result', models.CharField(blank=True, max_length=30, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
