# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usasui', '0002_testreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='testrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usasui.TestRequest'),
        ),
    ]
